### ISSUE TITLE
[RUNTIME] java.lang.NullPointerException: Attempt to read from field 'boolean BSGameState.inGame' on a null object reference

### ISSUE THREAD

**Issue by Kai-Richardson** [Cryptix808/BattleShip#4]
Stack Trace:
```
2010-01-21 21:11:07.358 22445-22445/com.example.battleship E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to read from field 'boolean com.example.battleship.battleship.BSGameState.inGame' on a null object reference
        at com.example.battleship.battleship.BSHumanPlayer.onTouch(BSHumanPlayer.java:65)
        at android.view.View.dispatchTouchEvent(View.java:10053)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3101)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
        at android.view.View.dispatchPointerEvent(View.java:10293)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4354)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4467)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4524)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4354)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6825)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6799)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6742)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6997)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:151)
        at android.app.ActivityThread.main(ActivityThread.java:6304)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
2010-01-21 21:11:07.359 22445-22445/com.example.battleship E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.battleship, PID: 22445
    java.lang.NullPointerException: Attempt to read from field 'boolean com.example.battleship.battleship.BSGameState.inGame' on a null object reference
        at com.example.battleship.battleship.BSHumanPlayer.onTouch(BSHumanPlayer.java:65)
        at android.view.View.dispatchTouchEvent(View.java:10053)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3101)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
        at android.view.View.dispatchPointerEvent(View.java:10293)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4354)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4467)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4524)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4354)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6825)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6799)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6742)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6997)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:151)
        at android.app.ActivityThread.main(ActivityThread.java:6304)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by NateKliner** [comment]
Not enough information to fix this. Closing.
